import { Sticker, Board } from '../types';

export const INITIAL_STICKERS: Sticker[] = [
  {
    id: 'sticker-1',
    name: 'Barnaby',
    animalType: 'cat',
    breed: 'Ginger Tabby',
    personality: 'Sunbeam Connoisseur & Fence Lounger',
    tags: ['Ginger', 'Friendly', 'Neighborhood Legend', 'Chonky'],
    isFavorite: true,
    imageUri: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80',
    originalUri: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=80',
    borderStyle: {
      width: 5,
      color: '#FFFFFF',
      shadow: true,
      glow: true,
      glowColor: 'rgba(217, 119, 6, 0.3)',
    },
    location: {
      latitude: 37.7749,
      longitude: -122.4194,
      neighborhood: 'Mission District',
      city: 'San Francisco',
      addressName: 'Sunny Alley by Valencia',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2, // 2 days ago
    notes: 'Greets every commuter at 8am sharp. Loves gentle chin scratches.',
    rescueStatus: 'community_resident',
  },
  {
    id: 'sticker-2',
    name: 'Mochi',
    animalType: 'cat',
    breed: 'Calico Bobtail',
    personality: 'Sleepy Baker & Box Inspector',
    tags: ['Calico', 'Sleepy', 'Patio Guardian'],
    isFavorite: true,
    imageUri: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=600&q=80',
    originalUri: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=1200&q=80',
    borderStyle: {
      width: 4,
      color: '#FFFFFF',
      shadow: true,
      glow: false,
    },
    location: {
      latitude: 37.7795,
      longitude: -122.4235,
      neighborhood: 'Hayes Valley',
      city: 'San Francisco',
      addressName: 'Artisan Bakery Flower Bed',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    notes: 'Takes afternoon naps nestled inside lavender planters.',
    rescueStatus: 'friendly_stray',
  },
  {
    id: 'sticker-3',
    name: 'Captain Klaus',
    animalType: 'dog',
    breed: 'Corgi Mix',
    personality: 'Chief Happiness Officer',
    tags: ['Energetic', 'Fluffy', 'Rescue Story'],
    isFavorite: false,
    imageUri: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80',
    originalUri: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1200&q=80',
    borderStyle: {
      width: 5,
      color: '#FFFFFF',
      shadow: true,
      glow: false,
    },
    location: {
      latitude: 37.7698,
      longitude: -122.4467,
      neighborhood: 'Buena Vista Park',
      city: 'San Francisco',
      addressName: 'Pine Grove Trail',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    notes: 'Adopted from the bay sanctuary last spring. Loves chasing tennis balls.',
    rescueStatus: 'rescued',
  },
  {
    id: 'sticker-4',
    name: 'Luna',
    animalType: 'cat',
    breed: 'Bombay Velvet',
    personality: 'Mysterious Night Stalker',
    tags: ['Black Cat', 'Graceful', 'Golden Eyes'],
    isFavorite: true,
    imageUri: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=600&q=80',
    originalUri: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=80',
    borderStyle: {
      width: 6,
      color: '#FEF3C7',
      shadow: true,
      glow: true,
      glowColor: 'rgba(245, 158, 11, 0.4)',
    },
    location: {
      latitude: 37.7601,
      longitude: -122.4211,
      neighborhood: 'Dolores Heights',
      city: 'San Francisco',
      addressName: 'Palm Tree Sanctuary',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
    notes: 'Silent as a cloud. Appears whenever canned tuna is opened nearby.',
    rescueStatus: 'community_resident',
  },
  {
    id: 'sticker-5',
    name: 'Pip',
    animalType: 'bunny',
    breed: 'Holland Lop',
    personality: 'Tiny Meadow Acrobat',
    tags: ['Bunny', 'Garden Resident', 'Gentle'],
    isFavorite: false,
    imageUri: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=600&q=80',
    originalUri: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=1200&q=80',
    borderStyle: {
      width: 4,
      color: '#FFFFFF',
      shadow: true,
      glow: false,
    },
    location: {
      latitude: 37.7712,
      longitude: -122.4344,
      neighborhood: 'Corona Heights',
      city: 'San Francisco',
      addressName: 'Community Herb Garden',
    },
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
    notes: 'Snacks on dandelion greens every sunrise.',
    rescueStatus: 'beloved_pet',
  },
];

export const INITIAL_BOARDS: Board[] = [
  {
    id: 'board-neighborhood',
    title: 'Neighborhood Whiskers',
    theme: 'neighborhood',
    description: 'The beloved community cats and street wanderers of the block.',
    pattern: 'dots',
    backgroundColor: '#FAF8F5',
    stickers: [
      {
        id: 'bs-1',
        stickerId: 'sticker-1',
        x: 60,
        y: 120,
        scale: 1.15,
        rotation: -4,
        zIndex: 1,
      },
      {
        id: 'bs-2',
        stickerId: 'sticker-2',
        x: 210,
        y: 190,
        scale: 0.95,
        rotation: 6,
        zIndex: 2,
      },
      {
        id: 'bs-3',
        stickerId: 'sticker-4',
        x: 100,
        y: 340,
        scale: 1.05,
        rotation: -8,
        zIndex: 3,
      },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    updatedAt: Date.now(),
  },
  {
    id: 'board-street',
    title: 'Park Patrol',
    theme: 'street',
    description: 'Adventures from Buena Vista & Dolores parks.',
    pattern: 'cork',
    backgroundColor: '#F4EFEA',
    stickers: [
      {
        id: 'bs-4',
        stickerId: 'sticker-3',
        x: 120,
        y: 160,
        scale: 1.2,
        rotation: 3,
        zIndex: 1,
      },
      {
        id: 'bs-5',
        stickerId: 'sticker-5',
        x: 220,
        y: 310,
        scale: 1.0,
        rotation: -5,
        zIndex: 2,
      },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
    updatedAt: Date.now(),
  },
  {
    id: 'board-my-pets',
    title: 'My Sweet Family',
    theme: 'pets',
    description: 'Our forever fur babies on their dedicated board.',
    pattern: 'grid',
    backgroundColor: '#FFFFFF',
    stickers: [
      {
        id: 'bs-6',
        stickerId: 'sticker-1',
        x: 150,
        y: 220,
        scale: 1.3,
        rotation: 0,
        zIndex: 1,
      },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
    updatedAt: Date.now(),
  },
];
